
# husk, at hvis du ændrer i noget i dinne konfigurationsfil imens serveren er oppe, kræver det et reload via. /am reload

# skal security være slået til på serveren.
# syntax: true / false
security-enabled: true

# skal cancelled chat events der indeholder sårbare serverting, såsom
# op/deop af spillere eller kommandoer skrevet af console, blive blokeret.
# obs: hvis du ændrer i denne, kræver det genstart af serveren.
# syntax: true / false
prevent-cancelled-malicious-chat-event: true

# skal OP proxy blocker være slået til på serveren. Det betyder, at du kan
# vælge i mellem specifikke personer som kan være OP på serveren, og alle
# andre vil blive blokeret. skriv de tilladte spillere/uuids under "target".
# syntax: true / false
op-proxy-blocker: true

target: []
# eksempel (husk at fjern "[]"):
# - Alek05
# - c3e9356e-841c-4a9f-8805-f4c5f0ea1255

