name: AntiMalware
version: 2.1.0
author: Alek05
website: https://www.spigotmc.org/resources/antimalware.109025/
main: me.alek.AntiMalwarePlugin
load: STARTUP
loadbefore: [EssentialsGroupManager, LuckPerms]
depend: []
softdepend: []
commands:
  antimalware:
    aliases: [am]

