name: AntiMalware
version: 2.1.0
author: Alek05
website: https://www.spigotmc.org/resources/antimalware.109025/
main: me.alek.antimalware.AntiMalwarePlugin
load: STARTUP
loadbefore: [HamsterAPI, GroupManager, LuckPerms, FastAsyncWorldEdit, WorldEdit, ViaVersion, ExploitFixer, ProtocolLib]
depend: []
softdepend: []
commands:
  am:
    aliases: [antimalware]

